[2025-06-10 13:42:06,634] smoke.utils.envs INFO: Using a generated random seed 6804819
[2025-06-10 13:46:37,040] smoke.utils.check_point INFO: Loading checkpoint from catalog://ImageNetPretrained/DLA34
[2025-06-10 13:46:37,055] smoke.utils.check_point INFO: catalog://ImageNetPretrained/DLA34 points to http://dl.yf.io/dla/models/imagenet/dla34-ba72cf86.pth
Downloading: "http://dl.yf.io/dla/models/imagenet/dla34-ba72cf86.pth" to /ifxhome/hotait/.torch/models/dla34-ba72cf86.pth
Traceback (most recent call last):
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/plain_train_net.py", line 100, in <module>
    args=(args,),
  File "/home/sfusion/users/hassan/CodeBase/SMOKE/smoke/engine/launch.py", line 56, in launch
    main_func(*args)
  File "tools/plain_train_net.py", line 78, in main
    _ = checkpointer.load(ckpt, use_latest=args.ckpt is None)
  File "/home/sfusion/users/hassan/CodeBase/SMOKE/smoke/utils/check_point.py", line 59, in load
    checkpoint = self._load_file(f)
  File "/home/sfusion/users/hassan/CodeBase/SMOKE/smoke/utils/check_point.py", line 125, in _load_file
    cached_f = cache_url(f)
  File "/home/sfusion/users/hassan/CodeBase/SMOKE/smoke/utils/model_zoo.py", line 54, in cache_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/sfusion/users/hassan/envs/venv_smoke/lib/python3.6/site-packages/torch/hub.py", line 384, in download_url_to_file
    u = urlopen(url)
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/opt/python/3.6.2/linux70_64/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
